### ISSUE TITLE
Get equation's unknown variables

### ISSUE THREAD

**Issue by samuelmtimbo** [arthanzel/evaluatex#2]
Given an equation string like "x^2 + y", I need to find out the list of its unknown variables such as `["x", "y"]` in this example. I feel this is something already being done somewhere in evaluatex code, but I couldn't find a public function or the correspondent internal code. This function should work with any valid evaluatex expression. Is that something useful to add to the interface? If not, could you point me out the file where I can find this logic so I can abstract that in my codebase?

**Comment by arthanzel** [comment]
Thank you for this suggestion!

When you compile a string into a function, the resulting function has [a few handy fields](https://github.com/arthanzel/evaluatex/blob/master/src/evaluatex.js#L17) like `ast` and `tokens` that allow you to inspect the compiled function's intermediate representations. Evaluatex replaces [known named variables](https://github.com/arthanzel/evaluatex/blob/master/src/lexer.js#L125) at compile-time in the lexer and retains the remaining unknown variables as "symbol" tokens. You could define a function, or perhaps contribute a method on the compiled function [here](https://github.com/arthanzel/evaluatex/blob/master/src/evaluatex.js#L17) that scans through the token list, filters `token.type === Token.TYPE_SYMBOL`, and collects unique `token.value`. This should list the names of unknown variables. Something like:

```javascript
new Set(evaluatex("2x+y+y")
  .tokens
  .filter(t => t.type === "SYMBOL")
  .map(t => t.value)
)
// => Set { 'x', 'y' }
```

For compatibility purposes, a PR for this should use regular loops instead of `filter`/`map` and an object instead of `Set` to eliminate duplicates.

Perhaps the documentation should also be amended to reflect the availability of `ast`, `tokens`, and `expression` members on the compiled function.

**Comment by samuelmtimbo** [comment]
I tried what you suggested in my codebase and it worked alright! Thank you! I am not sure if I should PR it since it is such a simple function once you know about `tokens`. I concur it would be helpful to refer to the `ast`, `tokens` and `expression` fields in the documentation.
